<?php get_header(); ?>

<main class="wrap">

  <!-- HERO -->
  <section class="hero">
    <p class="kicker">SAVAGE BY DESIGN — TERMS OF SERVICE</p>
    
    <h1>Terms of Service</h1>
    
    <p class="subhead">
      <strong>Last Updated: January 4, 2026</strong>
    </p>
  </section>

  <!-- AGREEMENT TO TERMS -->
  <section class="section">
    <h2>Agreement to Terms</h2>
    <p>By using Savage By Design ("the App"), you agree to these Terms of Service. If you do not agree, do not use the App.</p>
  </section>

  <!-- DESCRIPTION OF SERVICE -->
  <section class="section">
    <h2>Description of Service</h2>
    <p>Savage By Design is a workout tracking application that helps users:</p>
    <ul>
      <li>Create and manage training blocks</li>
      <li>Track workout sessions</li>
      <li>Import workout plans from external sources</li>
      <li>Analyze training progress</li>
    </ul>
  </section>

  <!-- SUBSCRIPTION SERVICE -->
  <section class="section section-dark">
    <h2>Subscription Service</h2>
    
    <h3>What You Get</h3>
    <p>The Pro subscription unlocks advanced features including:</p>
    
    <h4>Currently Implemented</h4>
    <ul>
      <li><strong>AI-Assisted Plan Ingestion</strong>: Import and parse workout plans from JSON files generated by AI assistants</li>
      <li><strong>JSON Workout Import</strong>: Paste or upload JSON workout plans directly into the app</li>
      <li><strong>AI Prompt Templates</strong>: Copy-paste ready prompts for generating structured workout blocks</li>
      <li><strong>Block Library Management</strong>: Save and organize AI-generated training blocks</li>
    </ul>

    <h4>Planned Features (Future Release)</h4>
    <ul>
      <li><strong>Automated Review & Modifications</strong>: Smart suggestions for plan optimization</li>
      <li><strong>Intelligent Progress Analysis</strong>: Advanced analytics and tracking</li>
      <li><strong>Advanced Block History</strong>: Comprehensive workout history</li>
      <li><strong>Enhanced Dashboards</strong>: Advanced visualization and reporting</li>
    </ul>

    <h3>What You Don't Get</h3>
    <p>The subscription does NOT include:</p>
    <ul>
      <li>Access to AI models or LLM services</li>
      <li>External content generation</li>
      <li>Personal training or coaching services</li>
      <li>Third-party integrations or services</li>
    </ul>
  </section>

  <!-- PRICING AND PAYMENT -->
  <section class="section">
    <h2>Pricing and Payment</h2>
    <ul>
      <li>Monthly subscription pricing is set in App Store Connect</li>
      <li>15-day free trial for eligible users</li>
      <li>Payment processed through Apple In-App Purchase</li>
      <li>Subscription automatically renews unless cancelled</li>
      <li>Cancel anytime through Apple's subscription management</li>
    </ul>
  </section>

  <!-- TRIAL PERIOD -->
  <section class="section">
    <h2>Trial Period</h2>
    <ul>
      <li>New users are eligible for a 15-day free trial</li>
      <li>Trial converts to paid subscription automatically unless cancelled</li>
      <li>Cancel anytime during trial period without charge</li>
      <li>Previous subscribers are not eligible for additional trials</li>
    </ul>
  </section>

  <!-- CANCELLATION AND REFUNDS -->
  <section class="section section-dark">
    <h2>Cancellation and Refunds</h2>
    <ul>
      <li>Cancel anytime through Settings > [Your Name] > Subscriptions</li>
      <li>Subscription remains active until end of current billing period</li>
      <li>No refunds for partial periods</li>
      <li>Refund requests must be made through Apple</li>
    </ul>
  </section>

  <!-- USER RESPONSIBILITIES -->
  <section class="section">
    <h2>User Responsibilities</h2>
    <p>You agree to:</p>
    <ul>
      <li>Use the App for lawful purposes only</li>
      <li>Not attempt to reverse engineer or modify the App</li>
      <li>Not share your subscription access</li>
      <li>Not use the App to harm others</li>
      <li>Maintain the security of your device</li>
    </ul>
  </section>

  <!-- CONTENT AND INTELLECTUAL PROPERTY -->
  <section class="section">
    <h2>Content and Intellectual Property</h2>
    
    <h3>Your Content</h3>
    <ul>
      <li>You retain ownership of all workout data you create</li>
      <li>You are responsible for any content you import</li>
      <li>You grant us no rights to your content</li>
    </ul>

    <h3>Our Content</h3>
    <ul>
      <li>The App and its features are protected by copyright</li>
      <li>You may not copy, modify, or distribute the App</li>
      <li>Brand names and logos are our property</li>
    </ul>

    <h3>Imported Content</h3>
    <p>When importing workout plans:</p>
    <ul>
      <li>You are responsible for ensuring you have rights to use the content</li>
      <li>You must not import copyrighted content without permission</li>
      <li>External content is provided by third parties (like AI assistants), not by us</li>
      <li>We are not responsible for the accuracy or safety of imported content</li>
    </ul>
  </section>

  <!-- DISCLAIMER OF WARRANTIES -->
  <section class="section section-dark">
    <h2>Disclaimer of Warranties</h2>
    <p><strong>THE APP IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND.</strong></p>
    <ul>
      <li>We do not guarantee the App will be error-free or uninterrupted</li>
      <li>We do not guarantee the accuracy of workout plans or advice</li>
      <li>We are not responsible for injuries resulting from app use</li>
      <li>Always consult a healthcare professional before starting any fitness program</li>
    </ul>
  </section>

  <!-- LIMITATION OF LIABILITY -->
  <section class="section">
    <h2>Limitation of Liability</h2>
    <p><strong>TO THE MAXIMUM EXTENT PERMITTED BY LAW:</strong></p>
    <ul>
      <li>We are not liable for any indirect, incidental, or consequential damages</li>
      <li>Our total liability shall not exceed the amount you paid for the subscription</li>
      <li>We are not liable for injuries or health issues resulting from workouts</li>
    </ul>
  </section>

  <!-- HEALTH AND SAFETY -->
  <section class="section section-dark">
    <h2>Health and Safety</h2>
    <p><strong>IMPORTANT:</strong></p>
    <ul>
      <li>Consult a physician before starting any exercise program</li>
      <li>Stop exercising if you feel pain or discomfort</li>
      <li>The App provides tools only, not medical or fitness advice</li>
      <li>We are not responsible for injuries or health issues</li>
    </ul>
  </section>

  <!-- CHANGES TO TERMS -->
  <section class="section">
    <h2>Changes to Terms</h2>
    <p>We may modify these terms at any time. Continued use of the App after changes constitutes acceptance of new terms.</p>
  </section>

  <!-- TERMINATION -->
  <section class="section">
    <h2>Termination</h2>
    <p>We may terminate or suspend access to the App at any time for:</p>
    <ul>
      <li>Violation of these terms</li>
      <li>Fraudulent activity</li>
      <li>Any other reason at our discretion</li>
    </ul>
  </section>

  <!-- GOVERNING LAW -->
  <section class="section section-dark">
    <h2>Governing Law</h2>
    <p>These terms are governed by the laws of the United States.</p>
  </section>

  <!-- CONTACT -->
  <section class="section">
    <h2>Contact</h2>
    <p>For questions about these terms, contact:</p>
    <ul>
      <li><strong>Email:</strong> <a href="mailto:savagesbydesignhq@gmail.com">savagesbydesignhq@gmail.com</a></li>
    </ul>
  </section>

  <!-- APPLE REQUIRED TERMS -->
  <section class="section section-dark">
    <h2>Apple Required Terms</h2>
    
    <h3>In-App Purchase Terms</h3>
    <ul>
      <li>All purchases are processed by Apple</li>
      <li>Apple's Terms of Sale apply: <a href="https://www.apple.com/legal/internet-services/itunes/">https://www.apple.com/legal/internet-services/itunes/</a></li>
      <li>Subscriptions automatically renew unless cancelled at least 24 hours before the end of the current period</li>
      <li>Your account will be charged for renewal within 24 hours prior to the end of the current period</li>
      <li>Manage subscriptions in your Apple account settings</li>
    </ul>

    <h3>Apple Privacy Policy</h3>
    <p>Apple's privacy policy applies to all payment processing: <a href="https://www.apple.com/legal/privacy/">https://www.apple.com/legal/privacy/</a></p>
  </section>

  <!-- CLOSER -->
  <section class="section closer">
    <div class="cta">
      <a class="btn btn-ghost" href="/">Back to Home</a>
      <a class="btn btn-ghost" href="/privacy/">Privacy Policy</a>
      <a class="btn btn-ghost" href="/app/">About the App</a>
    </div>
  </section>

</main>

<?php get_footer(); ?>
